channels:
  - "-1003596110991"

# Regex notes:
# case_insensitive is assumed true in code logic unless specified otherwise
products:
  - name: "Test Product"
    regex: "oi"
  - name: "RTX 5070"
    regex: "5070"
